---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
library(skimr)
library(performance)
library(emmeans)
library(multcomp)
library(readxl)
```


# PH

```{r}
m_ls1<- lm(ph~fp2, data=fp1)
summary (m_ls1)
anova (m_ls1)
library(emmeans)
mm1<- emmeans(m_ls1, ~ fp2, type="response")
res1<-cld(mm1, Letters=letters, reverse=TRUE, alpha=.05)
res1
```

```{r}
res1%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= ph))+
labs(x="Ppd-A1GS105", y="ph")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=ph))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-ph.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-ph.png",width= 1000, height= 900)
boxplot(data= fp1,ph~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "ph",
col=c("green", "violet", "yellow"))
dev.off()
```

# PROTEINA

```{r}
m_ls2<- lm(proteina~fp2, data=fp1)
summary (m_ls2)
anova (m_ls2)
library(emmeans)
mm2<- emmeans(m_ls2, ~ fp2, type="response")
res2<-cld(mm2, Letters=letters, reverse=TRUE, alpha=.05)
res2
```

```{r}
res2%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= proteina))+
labs(x="Ppd-A1GS105", y="proteina")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=proteina))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/2- Ppd-A1GS105- Tukey-proteina.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-proteina.png",width= 1000, height= 900)
boxplot(data= fp1,proteina~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "proteina",
col=c("green", "violet", "yellow"))
dev.off()
```

# ESPIGAZON

```{r}
m_ls3<- lm(espigazon~fp2, data=fp1)
summary (m_ls3)
anova (m_ls3)
library(emmeans)
mm3<- emmeans(m_ls3, ~ fp2, type="response")
res3<-cld(mm3, Letters=letters, reverse=TRUE, alpha=.05)
res3
```

```{r}
res3%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= espigazon))+
labs(x="Ppd-A1GS105", y="espigazon")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=espigazon))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/3- Ppd-A1GS105- Tukey-espigazon.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-espigazon.png",width= 1000, height= 900)
boxplot(data= fp1,espigazon~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "espigazon",
col=c("green", "violet", "yellow"))
dev.off()
```

# MADUREZ

```{r}
m_ls4<- lm(madurez~fp2, data=fp1)
summary (m_ls4)
anova (m_ls4)
library(emmeans)
mm4<- emmeans(m_ls4, ~ fp2, type="response")
res4<-cld(mm4, Letters=letters, reverse=TRUE, alpha=.05)
res4
```

```{r}
res4%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= madurez))+
labs(x="Ppd-A1GS105", y="madurez")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=madurez))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/4- Ppd-A1GS105- Tukey-madurez.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-madurez.png",width= 1000, height= 900)
boxplot(data= fp1,madurez~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "madurez",
col=c("green", "violet", "yellow"))
dev.off()
```

# ALTURA

```{r}
m_ls5<- lm(altura~fp2, data=fp1)
summary (m_ls5)
anova (m_ls5)
library(emmeans)
mm5<- emmeans(m_ls5, ~ fp2, type="response")
res5<-cld(mm5, Letters=letters, reverse=TRUE, alpha=.05)
res5
```

```{r}
res5%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= altura))+
labs(x="Ppd-A1GS105", y="altura")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=altura))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/5- Ppd-A1GS105- Tukey-altura.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-altura.png",width= 1000, height= 900)
boxplot(data= fp1,altura~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "altura",
col=c("green", "violet", "yellow"))
dev.off()
```

# KG_PARCELA

```{r}
m_ls6<- lm(kg_parcela~fp2, data=fp1)
summary (m_ls6)
anova (m_ls6)
library(emmeans)
mm6<- emmeans(m_ls6, ~ fp2, type="response")
res6<-cld(mm6, Letters=letters, reverse=TRUE, alpha=.05)
res6
```

```{r}
res6%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= kg_parcela))+
labs(x="Ppd-A1GS105", y="kg_parcela")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=kg_parcela))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/6- Ppd-A1GS105- Tukey-kg_parcela.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-kg_parcela.png",width= 1000, height= 900)
boxplot(data= fp1,kg_parcela~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "kg_parcela",
col=c("green", "violet", "yellow"))
dev.off()
```

# PMG

```{r}
m_ls7<- lm(pmg~fp2, data=fp1)
summary (m_ls7)
anova (m_ls7)
library(emmeans)
mm7<- emmeans(m_ls7, ~ fp2, type="response")
res7<-cld(mm7, Letters=letters, reverse=TRUE, alpha=.05)
res7
```

```{r}
res7%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= pmg))+
labs(x="Ppd-A1GS105", y="pmg")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=pmg))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/7- Ppd-A1GS105- Tukey-pmg.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-pmg.png",width= 1000, height= 900)
boxplot(data= fp1,pmg~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "pmg",
col=c("green", "violet", "yellow"))
dev.off()
```

# BA

```{r}
m_ls8<- lm(ba~fp2, data=fp1)
summary (m_ls8)
anova (m_ls8)
library(emmeans)
mm8<- emmeans(m_ls8, ~ fp2, type="response")
res8<-cld(mm8, Letters=letters, reverse=TRUE, alpha=.05)
res8
```

```{r}
res8%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= ba))+
labs(x="Ppd-A1GS105", y="ba")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=ba))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/8- Ppd-A1GS105- Tukey-ba.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-ba.png",width= 1000, height= 900)
boxplot(data= fp1,ba~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "ba",
col=c("green", "violet", "yellow"))
dev.off()
```

# IC

```{r}
m_ls9<- lm(ic~fp2, data=fp1)
summary (m_ls9)
anova (m_ls9)
library(emmeans)
mm9<- emmeans(m_ls9, ~ fp2, type="response")
res9<-cld(mm9, Letters=letters, reverse=TRUE, alpha=.05)
res9
```

```{r}
res9%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= ic))+
labs(x="Ppd-A1GS105", y="ic")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=ic))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/9- Ppd-A1GS105- Tukey-ic.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-ic.png",width= 1000, height= 900)
boxplot(data= fp1,ic~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "ic",
col=c("green", "violet", "yellow"))
dev.off()
```

# ESP_M2

```{r}
m_ls10<- lm(esp_m2~fp2, data=fp1)
summary (m_ls10)
anova (m_ls10)
library(emmeans)
mm10<- emmeans(m_ls10, ~ fp2, type="response")
res10<-cld(mm10, Letters=letters, reverse=TRUE, alpha=.05)
res10
```

```{r}
res10%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= esp_m2))+
labs(x="Ppd-A1GS105", y="esp_m2")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=esp_m2))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/10- Ppd-A1GS105- Tukey-esp_m2.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-esp_m2.png",width= 1000, height= 900)
boxplot(data= fp1,esp_m2~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "esp_m2",
col=c("green", "violet", "yellow"))
dev.off()
```

# GUILLAS_ESP

```{r}
m_ls11<- lm(guillas_esp~fp2, data=fp1)
summary (m_ls11)
anova (m_ls11)
library(emmeans)
mm11<- emmeans(m_ls11, ~ fp2, type="response")
res11<-cld(mm11, Letters=letters, reverse=TRUE, alpha=.05)
res11
```

```{r}
res11%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= guillas_esp))+
labs(x="Ppd-A1GS105", y="guillas_esp")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=guillas_esp))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/11- Ppd-A1GS105- Tukey-guillas_esp.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-guillas_esp.png",width= 1000, height= 900)
boxplot(data= fp1,guillas_esp~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "guillas_esp",
col=c("green", "violet", "yellow"))
dev.off()
```

# GRAN_ESP

```{r}
m_ls12<- lm(gran_esp~fp2, data=fp1)
summary (m_ls12)
anova (m_ls12)
library(emmeans)
mm12<- emmeans(m_ls12, ~ fp2, type="response")
res12<-cld(mm12, Letters=letters, reverse=TRUE, alpha=.05)
res12
```

```{r}
res12%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= gran_esp))+
labs(x="Ppd-A1GS105", y="gran_esp")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=gran_esp))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/12- Ppd-A1GS105- Tukey-gran_esp.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-gran_esp.png",width= 1000, height= 900)
boxplot(data= fp1,gran_esp~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "gran_esp",
col=c("green", "violet", "yellow"))
dev.off()
```

# RINDE_ESP

```{r}
m_ls13<- lm(rinde_esp~fp2, data=fp1)
summary (m_ls13)
anova (m_ls13)
library(emmeans)
mm13<- emmeans(m_ls13, ~ fp2, type="response")
res13<-cld(mm13, Letters=letters, reverse=TRUE, alpha=.05)
res13
```

```{r}
res13%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= rinde_esp))+
labs(x="Ppd-A1GS105", y="rinde_esp")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=rinde_esp))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/13- Ppd-A1GS105- Tukey-rinde_esp.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-rinde_esp.png",width= 1000, height= 900)
boxplot(data= fp1,rinde_esp~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "rinde_esp",
col=c("green", "violet", "yellow"))
dev.off()
```

# G_M2

```{r}
m_ls14<- lm(g_m2~fp2, data=fp1)
summary (m_ls14)
anova (m_ls14)
library(emmeans)
mm14<- emmeans(m_ls14, ~ fp2, type="response")
res14<-cld(mm14, Letters=letters, reverse=TRUE, alpha=.05)
res14
```

```{r}
res14%>%
  ggplot()+
  aes(x=fp2,y=emmean)+
geom_boxplot(data=fp1,mapping=aes(x=fp2,y= g_m2))+
labs(x="Ppd-A1GS105", y="g_m2")+
  geom_text(aes(label=str_squish(.group)),
            angle=90,vjust=-1)+
  geom_jitter(data=fp1,width  =.1, alpha =.5,
              aes(y=g_m2))+
  theme_bw()
```

```{r}
ggsave(last_plot(),file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/14- Ppd-A1GS105- Tukey-g_m2.png", w=300, h=250, units="mm", dpi=300)
```

```{r}
png(file="7- Anova para genes/1- PpdA1/Gráficos/Ppd-A1GS105 (wMAS000030)/1- Ppd-A1GS105- Tukey-Color-g_m2.png",width= 1000, height= 900)
boxplot(data= fp1,g_m2~fp2, main= "Diagrama de cajas para PpdA1-GS105", xlab="Alelos", ylab= "g_m2",
col=c("green", "violet", "yellow"))
dev.off()
```
